/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plataformakpn;

import JConnector.ConnectLine;
import JConnector.ConnectorContainer;
import JConnector.ConnectorPropertiesPanel;
import JConnector.DraggableLabel;
import JConnector.JConnector;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Daniel
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private int resizeMousePosition;

    public GUI() {
        initComponents();
        
          
        makeInvisible();
        initGlobalValues();
        
        
    /*    this.jPanelBoard.add(initConnectors(),
                             new GridBagConstraints(0, 0, 1, 1, 1, 1, GridBagConstraints.NORTHWEST, GridBagConstraints.BOTH, new Insets(5, 5, 5, 5), 0, 0));
      
        */

    }

    //http://java-sl.com/connector.html
    protected ConnectorContainer initConnectors() {
        JLabel b1 = new DraggableLabel("Source 1");
        b1.setBounds(10, 10, 100, 50);
        JLabel b2 = new DraggableLabel("Dest 1");
        b2.setBounds(200, 20, 100, 50);

        JConnector[] connectors = new JConnector[2];
//        JLabel b3=new DraggableLabel("Source 2");
//        b3.setBounds(200,500,100,25);
//        JLabel b4=new DraggableLabel("Dest 2");
//        b4.setBounds(400,300,100,25);
        connectors[0] = new JConnector(b1, b2, ConnectLine.LINE_ARROW_DEST, JConnector.CONNECT_LINE_TYPE_RECTANGULAR, Color.black);
        //      props = new ConnectorPropertiesPanel(connectors[0]);
//        connectors[1]=new JConnector(b3, b4, ConnectLine.LINE_ARROW_DEST, Color.blue);
        ConnectorContainer cc = new ConnectorContainer(connectors);
        //cc.setLayout(null);

        cc.add(b1);
        cc.add(b2);
        //cc.add(b3);
//        cc.add(b4);

       

        cc.setBorder(new EtchedBorder(EtchedBorder.LOWERED));

        //this.jPanel_Main.add(cc);

          
    
      //  this.jPanel_Main.add(b1);
      //  this.jPanel_Main.add(b2);

          return cc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Main = new javax.swing.JPanel();
        jPanelBoard = new javax.swing.JPanel();
        jLabelAddAux = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabelAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Main.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBoard.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBoard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBoard.setLayout(new java.awt.GridBagLayout());

        jLabelAddAux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N

        jButtonAdd.setText("jButton1");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabelAdd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelAddMouseDragged(evt);
            }
        });
        jLabelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAddMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MainLayout.createSequentialGroup()
                        .addComponent(jPanelBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddAux)
                            .addComponent(jLabelAdd)))
                    .addComponent(jButtonAdd)))
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButtonAdd)
                .addGap(31, 31, 31)
                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MainLayout.createSequentialGroup()
                        .addComponent(jLabelAdd)
                        .addGap(49, 49, 49)
                        .addComponent(jLabelAddAux))
                    .addComponent(jPanelBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1140, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabelAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddMouseReleased

        JLabel label = new JLabel();
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png")));
        label.setBounds(0, 0, 64, 64); //64x64

        label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent event) {
                label.setLocation(event.getXOnScreen() - resizeMousePosition, event.getYOnScreen() - resizeMousePosition);
            }
        });

        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLabel labelGet = (JLabel) evt.getSource();

                //Si toma el elemento
                labelGet.setText("hola soy yo");
                System.out.println("clicked");
            }
        });

        this.jPanel_Main.add(label);

        label.setLocation(evt.getXOnScreen() - resizeMousePosition, evt.getYOnScreen() - resizeMousePosition);

        this.jLabelAddAux.setVisible(false);


        /* label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelAddMouseDragged(evt);
            }
        }); */
        //System.out.println("ya debria verse");
    }//GEN-LAST:event_jLabelAddMouseReleased

    private void jLabelAddMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddMouseDragged
        System.out.println("Me estan moviendo: x:" + evt.getXOnScreen() + " y:" + evt.getYOnScreen());
        this.jLabelAddAux.setVisible(true);
        this.jLabelAddAux.setLocation(evt.getXOnScreen() - resizeMousePosition, evt.getYOnScreen() - resizeMousePosition);

    }//GEN-LAST:event_jLabelAddMouseDragged

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        
        System.out.println("Button");
        
     //   this.jPanelBoard.removeAll();
      /*  JLabel label = new DraggableLabel("");
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png")));
        label.setBounds(0, 0, 64, 64); //64x64
        
        this.jPanelBoard.add(label);

        label.setLocation(101,204);*/
      
       JConnector[] connectors = new JConnector[2];
        JLabel b1 = new DraggableLabel("Source 1");
        b1.setBounds(10, 10, 100, 50);
        JLabel b2 = new DraggableLabel("Dest 1");
        b2.setBounds(200, 20, 100, 50);

       

       connectors[0] = new JConnector(b1, b2, ConnectLine.LINE_ARROW_SOURCE, JConnector.CONNECT_LINE_TYPE_RECTANGULAR, Color.red);
        
       ConnectorContainer cc = new ConnectorContainer(connectors);
        cc.setLayout(null);

        cc.add(b1);
        cc.add(b2);
        

        cc.setBorder(new EtchedBorder(EtchedBorder.LOWERED));

         this.jPanelBoard.add(cc,
                             new GridBagConstraints(0, 1, 1, 1, 1, 1, GridBagConstraints.NORTHWEST, GridBagConstraints.BOTH, new Insets(5, 5, 5, 5), 0, 0));
    
     
         this.jPanelBoard.validate();
        this.jPanelBoard.updateUI();
        
      
       
    }//GEN-LAST:event_jButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelAddAux;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanel_Main;
    // End of variables declaration//GEN-END:variables

    private void makeInvisible() {
        this.jLabelAddAux.setVisible(false);
    }

    private void initGlobalValues() {
        this.resizeMousePosition = 40;
    }
}
