/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plataformakpn;

import javax.swing.JLabel;

/**
 *
 * @author Daniel
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    private int resizeMousePosition;
    
    public GUI() {
        initComponents(); 
        makeInvisible();
        initGlobalValues();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Main = new javax.swing.JPanel();
        jLabelAdd = new javax.swing.JLabel();
        jLabelAddAux = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Main.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabelAdd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelAddMouseDragged(evt);
            }
        });
        jLabelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAddMouseReleased(evt);
            }
        });

        jLabelAddAux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addComponent(jLabelAddAux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 972, Short.MAX_VALUE)
                .addComponent(jLabelAdd))
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MainLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabelAddAux))
                    .addGroup(jPanel_MainLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabelAdd)))
                .addContainerGap(411, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 1100, 567));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jLabelAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddMouseReleased
                
        JLabel label = new JLabel();
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png")));
        label.setBounds(0, 0, 64, 64); //64x64
        
        
        label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent event) {
                label.setLocation(event.getXOnScreen()-resizeMousePosition, event.getYOnScreen()-resizeMousePosition);
            }     
        });
        
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JLabel labelGet = (JLabel) evt.getSource();
                
                //Si toma el elemento
                labelGet.setText("hola soy yo");
                System.out.println("clicked");
            }
        });
        

        

        this.jPanel_Main.add(label);

        this.jPanel_Main.revalidate();
        
        this.jPanel_Main.repaint();
        

        
        label.setLocation(evt.getXOnScreen()-resizeMousePosition, evt.getYOnScreen()-resizeMousePosition);
        
        this.jLabelAddAux.setVisible(false);
        

        /* label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelAddMouseDragged(evt);
            }
        }); */        

        //System.out.println("ya debria verse");
    }//GEN-LAST:event_jLabelAddMouseReleased

    private void jLabelAddMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddMouseDragged
        //System.out.println("Me estan moviendo: x:" + evt.getXOnScreen() + " y:" + evt.getYOnScreen());
        this.jLabelAddAux.setVisible(true);
        this.jLabelAddAux.setLocation(evt.getXOnScreen()-resizeMousePosition, evt.getYOnScreen()-resizeMousePosition);

    }//GEN-LAST:event_jLabelAddMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelAddAux;
    private javax.swing.JPanel jPanel_Main;
    // End of variables declaration//GEN-END:variables

    private void makeInvisible() {
        this.jLabelAddAux.setVisible(false);
    }

    private void initGlobalValues() {
        this.resizeMousePosition=40;
    }
}
